In [2]:
import pandas as pd

In [3]:
df = pd.read_excel('evaluation_results2.xlsx')

In [6]:
df.head(12)

,Dataset_Name,Number of Row,Precision,Degree,Number_Of_Features,Model,Dataset_split,MSE,MAE,R2 Score,preproccesing_time,execution_time,postproccesing_time,total_time
0,dataset_1.csv,20433,3,2,45,Neal,Train,0.028274,0.122607,0.497557,0.082205,0.672001,0.014145,0.768351
1,dataset_1.csv,20433,3,2,45,Neal,Test,0.028215,0.122829,0.514681,0.082205,0.672001,0.014145,0.768351
2,dataset_1.csv,20433,3,2,45,Fixstar,Train,0.018516,0.099188,0.670954,0.210173,6.034730,0.000999,6.245903
3,dataset_1.csv,20433,3,2,45,Fixstar,Test,0.019259,0.101329,0.668733,0.210173,6.034730,0.000999,6.245903
4,dataset_1.csv,20433,3,2,45,Sklearn,Train,0.016938,0.092703,0.698996,-,0.027901,-,0.027901
5,dataset_1.csv,20433,3,2,45,Sklearn,Test,0.017543,0.094886,0.698250,-,0.027901,-,0.027901
6,dataset_1.csv,20433,3,3,165,Neal,Train,0.024870,0.114924,0.558045,0.643584,10.727881,0.051449,11.422914
7,dataset_1.csv,20433,3,3,165,Neal,Test,0.025423,0.114883,0.562703,0.643584,10.727881,0.051449,11.422914
8,dataset_1.csv,20433,3,3,165,Fixstar,Train,0.017045,0.093560,0.697102,2.012789,8.032260,0.001,10.046049
9,dataset_1.csv,20433,3,3,165,Fixstar,Test,0.017687,0.095804,0.695759,2.012789,8.032260,0.001,10.046049
10,dataset_1.csv,20433,3,3,165,Sklearn,Train,0.014366,0.084938,0.744713,-,0.118789,-,0.118789
11,dataset_1.csv,20433,3,3,165,Sklearn,Test,0.016120,0.089149,0.722719,-,0.118789,-,0.118789